import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// Import Cera Pro fonts

const ceraPro = localFont({
  variable: "--font-cera-pro",
  src: [
    {
      path: "../public/cera-pro/CeraPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/cera-pro/CeraPro-Medium.otf",
      weight: "500",
      style: "normal",
    },
    // {
    //   path: "../public/cera-pro/CeraPro-Bold.otf",
    //   weight: "700",
    //   style: "normal",
    // },
    // {
    //   path: "../public/cera-pro/CeraPro-Black.otf",
    //   weight: "900",
    //   style: "normal",
    // },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ceraPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
